### ISSUE TITLE
[Feathure] Hide pin input support

### ISSUE THREAD

**Issue by Halimao** [fox-one/mixin-cli#6]
`--pin` flag doesn't hide pin content now, in my opinion, this is not secure.

using `--pin` without leave pin content, return error message following:
`execute failed: flag needs an argument: --pin`

**Comment by Halimao** [comment]
By the way, seems that v2 has remove "update pin" sub command?

**Comment by xwjdsh** [comment]
You can add the pin to your Keystore file, and then you don't need to set a pin from the command line.
```
{
  "pin":"CHANGE_ME",
  "client_id": "..."
  ...
}
```

**Comment by Halimao** [comment]
> You can add the pin to your Keystore file, and then you don't need to set a pin from the command line.
> 
> ```
> {
>   "pin":"CHANGE_ME",
>   "client_id": "..."
>   ...
> }
> ```

But store pin in the file is not secure too... also, [fox-one/mixin-sdk-go](https://github.com/fox-one/mixin-sdk-go/blob/master/keystore.go#L23) doestn't store pin in keystore

**Comment by xwjdsh** [comment]
> [fox-one/mixin-sdk-go](https://github.com/fox-one/mixin-sdk-go/blob/master/keystore.go#L23) doestn't store pin in keystore

Here it is https://github.com/fox-one/mixin-cli/blob/master/cmdutil/store.go#L16

You make sense. If the pin is required but is not set on the command line and in the file, maybe we should let the user provide pin input instead of returning an error.

@yiplee What's your opinion? I'd like to send PR if you agree.

**Comment by lyricat** [comment]
> maybe we should let the user provide pin input instead of returning an error.

vote for that

**Comment by Halimao** [comment]
> By the way, seems that v2 has remove "update pin" sub command?

"update pin" command is also helpful ☺

**Comment by yiplee** [comment]
>  If the pin is required but is not set on the command line and in the file, maybe we should let the user provide pin input instead of returning an error.

sounds good to me 👍 @xwjdsh
