### ISSUE TITLE
execute failed: unknown command "echo" for "mixin-cli"

### ISSUE THREAD

**Issue by LazzaroneS** [fox-one/mixin-cli#9]
It seems that the mixin-cli echo command doesn't work. as follows:
![can-not-echo](https://user-images.githubusercontent.com/41162617/216303559-8e853db2-ec0e-41db-a3fa-29061c3cc9f9.jpg)

**Comment by lyricat** [comment]
there is no `echo` command for mixin-cli. please check `mixin-cli help`

**Comment by LazzaroneS** [comment]
Ok, sorry, next time I will check help first.

**Comment by lyricat** [comment]
you're welcome. the description in the previous README.md was a bit confusing, it has been corrected.
